name: idaes-pse
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - idaes-pse
    - idaes-examples
    # - git+https://github.com/IDAES/examples.git@2.8_rel
    # - git+https://github.com/IDAES/idaes-pse.git@scaling_toolbox